String HomePageStyle = {
    "<html lang='en'>"
    "<head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>Document</title>"
    "<style>"
    "body {padding-bottom: 30px; margin: auto; background-color: black; color: white; font-family: Arial, sans-serif; display: flex; align-items: center; flex-direction: column; width: 60%;}"
    "form { width: 100%; display: flex; flex-direction: column; align-items: center; margin-top: 20px; }"
    "label { margin-bottom: 10px; font-size: 20px; }"
    ".input-group {width:100%; display: flex; flex-direction: column; align-items: center; }"
    "input[type='text'], input[type='number'] { font-size: 15px; font-weight: bold; padding: 15px; width: 100%; padding-left: 30px; margin-bottom: 10px; }"
    ".btn-submit { text-decoration: none; text-align: center; margin-top: 20px; padding: 10px 20px; font-size: 20px; background-color: #4caf50; border: none; color: white; cursor: pointer; border-radius: 5px;}"
    ".btn-submit:not(:disabled):hover { background-color: #216425; }"
    ".switch { width: 100%; position: relative; line-height: 22px; font-size: 16px; height: 22px; }"
    ".switch input { outline: 0; opacity: 0; width: 0; height: 0; }"
    ".slider { width: 50px; height: 30px; border-radius: 22px; cursor: pointer; background-color: grey; }"
    ".slider, .slider:before { display: inline-block; transition: 0.4s; }"
    ".slider:before { position: relative; content: ''; border-radius: 50%; height: 16px; width: 16px; left: 4px; top: 5px; background-color: #fff; }"
    "input:checked + .slider { background-color: #ff3034; }"
    "input:checked + .slider:before { -webkit-transform: translateX(26px); transform: translateX(26px); }"
    ".btn-submit:disabled { background-color: #216425; cursor: not-allowed;}"
    "table tr td{ padding: 10px;}"
    "table tr th, td:first-child{ width: 50%;}"
    ".disable{ pointer-events: none; background-color: #216425 !important;}"
    "table tr:nth-child(2) td:nth-child(2){ font-size: 30px; color: green;}"
    ".flex-direction-row{ display: flex; flex-direction:row !important}"
    ".mt-20{ margin-top: 20px;}"
    "</style>"
    "</head>"};

String HomePageScript = {
    "<script>"
    "const inputs=document.querySelectorAll('input[required]'); inputs.forEach(input=>{ input.addEventListener('invalid', function(){ this.setCustomValidity('Vui lòng nhập thông tin này');}); input.addEventListener('input', function(){ this.setCustomValidity('');});});"
    "const btnConnect=document.getElementById('btnConnect'); btnConnect.addEventListener('click', function(){ const ssid=document.getElementById('ssid').value; const password=document.getElementById('password').value; if(ssid=='' || password==''){ return} btnConnect.classList.add('disable'); btnConnect.value='Connecting...'});"
    "const speaker_volume_tag=document.getElementById('speaker-volume'); function showVal(newVal){ speaker_volume_tag.innerHTML=newVal;}"
    "const camera_status_label = document.getElementById('camera-status'); function changeStatusLabel(checkbox){ if(checkbox.checked){ camera_status_label.innerHTML = 'ON';} else{ camera_status_label.innerHTML = 'OFF';}}"
    "const btn_change_speaker_status = document.getElementById('btn-change-speaker-status');"
    "btn_change_speaker_status.addEventListener('click', function(){"
    "const speaker_status = document.getElementById('checkboxCamera').checked;"
    "const speaker_volume = document.getElementById('speaker-volume-range').value;" 
    "btn_change_speaker_status.classList.add('disable');"
    "btn_change_speaker_status.value='Updating...';"
    "fetch(`/speaker?speaker_status=${speaker_status}&speaker_volume=${speaker_volume}`,{method: 'GET'}) .then(response=>{ return response.json()}) .then(data=>{ console.log(data); btn_change_speaker_status.classList.remove('disable'); btn_change_speaker_status.value='Cập nhật'}) .catch(error=>{ console.log(error); btn_change_speaker_status.classList.remove('disable'); btn_change_speaker_status.value='Cập nhật'});"
    "});"
    "</script>"};
