String HomePageStyle = {
    "<html lang='en'>"
    "<head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>Document</title>"
    "<style>"
    "body { background-color: black; color: white; font-family: Arial, sans-serif; display: flex; align-items: center; flex-direction: column; width: 100%;}"
    "form { width: 60%; display: flex; flex-direction: column; align-items: center; margin-top: 20px; }"
    "label { margin-bottom: 10px; font-size: 20px; }"
    ".input-group {width:100%; display: flex; flex-direction: column; align-items: center; }"
    "input[type='text'], input[type='number'] { font-size: 15px; font-weight: bold; padding: 15px; width: 100%; padding-left: 30px; margin-bottom: 10px; }"
    "input[type='submit'] { text-decoration: none; text-align: center; margin-top: 20px; padding: 10px 20px; font-size: 20px; background-color: #4caf50; border: none; color: white; cursor: pointer; border-radius: 5px;}"
    "input[type='submit']:not(:disabled):hover { background-color: #216425; }"
    ".switch { width: 100%; position: relative; line-height: 22px; font-size: 16px; height: 22px; }"
    ".switch input { outline: 0; opacity: 0; width: 0; height: 0; }"
    ".slider { width: 50px; height: 30px; border-radius: 22px; cursor: pointer; background-color: grey; }"
    ".slider, .slider:before { display: inline-block; transition: 0.4s; }"
    ".slider:before { position: relative; content: ''; border-radius: 50%; height: 16px; width: 16px; left: 4px; top: 5px; background-color: #fff; }"
    "input:checked + .slider { background-color: #ff3034; }"
    "input:checked + .slider:before { -webkit-transform: translateX(26px); transform: translateX(26px); }"
    "input[type='submit']:disabled { background-color: #216425; cursor: not-allowed;}"
    "table tr td{ padding: 10px;}"
    "table tr th, td:first-child{ width: 50%;}"
    ".disable{ pointer-events: none; background-color: #216425 !important;}"
    "table tr:nth-child(2) td:nth-child(2){ font-size: 30px; color: green;}"
    "</style>"
    "</head>"};

String HomePageContent = {
    "<h1 style='text-align: center; font-size: 40px; margin-top: 100px'>Cấu hình module ESP8266</h1>"
    "<h2 style='text-align: center; font-size: 20px; margin-top: 20px'>Hãy nhập thông tin wifi</h2>"
    "<form action='/connect' method='POST'>"
    "<div class='input-group'><label for='ssid'>SSID:</label><input type='text' id='ssid' name='ssid' value='' placeholder='Enter Wifi name' required /></div>"
    "<div class='input-group'><label for='password'>Password:</label><input type='text' id='password' name='password' value='' placeholder='Enter Wifi password' required /></div>"
    "<input id = 'btnConnect' type='submit' value='Kết nối Wifi' class="
    ">"
    "</form>"
    "<table style='width:60%; border: 1px solid #00aeff; padding: 10px;'>"
    "<tr><th></th><th></th></tr>"
    "<tr><td>Trạng thái</td><td style='font-weight: bold; color: rgb(255, 0, 0);'>Chưa kết nối</td></tr>"
    "<tr><td>Tên wifi</td><td>?-?-?-?</td></tr>"
    "<tr><td>Mật khẩu wifi</td><td>?-?-?-?</td></tr>"
    "<tr><td>Địa chỉ IP</td><td>?-?-?-?</td></tr>"
    "</table>"};

String HomePageScript = {
    "<script>"
    "const inputs=document.querySelectorAll('input[required]'); inputs.forEach(input=>{ input.addEventListener('invalid', function(){ this.setCustomValidity('Vui lòng nhập thông tin này');}); input.addEventListener('input', function(){ this.setCustomValidity('');});});"
    "const btnConnect=document.getElementById('btnConnect'); btnConnect.addEventListener('click', function(){ const ssid=document.getElementById('ssid').value; const password=document.getElementById('password').value; if(ssid=='' || password==''){ return} btnConnect.classList.add('disable'); btnConnect.value='Connecting...'});"
    "</script>"};
